apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-staging-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/medyassine-bensaid/mlops-manifests.git"
    targetRevision: main
    path: apps/staging-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
