apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: minio
    targetRevision: "11.0.0"
    helm:
      values: |
        auth:
          rootUser: minio
          rootPassword: minioStrongPass123!
        service:
          type: ClusterIP
        defaultBuckets: "mlflow"
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
